# Generated by Django 4.2.14 on 2024-07-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='symbol',
            field=models.ImageField(default='cercle.jpg', upload_to='symbols'),
        ),
    ]
