# Generated by Django 4.2.14 on 2024-07-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='scores',
            field=models.TextField(default='{}'),
        ),
    ]
