# Generated by Django 4.2.14 on 2024-07-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_content_post_access_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gameOver',
            field=models.BooleanField(default=False),
        ),
    ]
