# Generated by Django 4.2.14 on 2024-07-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_gameover'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='moves_played',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
