# Generated by Django 4.2.14 on 2024-07-30 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='blog.tournament'),
        ),
    ]
