# Generated by Django 4.2.14 on 2024-07-30 22:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_post_player3_post_player4'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='losers',
            field=models.ManyToManyField(blank=True, related_name='losers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='grid_size',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
