# Generated by Django 4.2.14 on 2024-07-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_losers_alter_tournament_grid_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='grid_size',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
