# Generated by Django 4.2.14 on 2024-07-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_tournament_grid_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date_played',
            field=models.DateField(blank=True, null=True),
        ),
    ]
